# Generated by Django 3.2.12 on 2022-02-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_experience_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencedescription',
            name='skills',
        ),
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.ManyToManyField(to='resume.TechSkill'),
        ),
    ]
