from datetime import timedelta, datetime
from django.db.models import Sum, F

import django_filters
from django.db.models import Max
from rest_framework import filters
from rest_framework import viewsets, permissions
from rest_framework.decorators import action
from rest_framework.response import Response

from api.timelogger.v1.serializers import TimeLoggerSerializer, SummarySerailizer
from timelogger.models import TimeLog

summary = [{'date': '2022-08-30', 'duration_in_minutes': 519, 'day': 1},
           {'date': '2022-08-31', 'duration_in_minutes': 588, 'day': 2},
           {'date': '2022-09-01', 'duration_in_minutes': 516, 'day': 3},
           {'date': '2022-09-02', 'duration_in_minutes': 592, 'day': 4},
           {'date': '2022-09-03', 'duration_in_minutes': 563, 'day': 5},
           {'date': '2022-09-04', 'duration_in_minutes': 507, 'day': 6},
           {'date': '2022-09-05', 'duration_in_minutes': 623, 'day': 0},
           {'date': '2022-09-06', 'duration_in_minutes': 607, 'day': 1},
           {'date': '2022-09-07', 'duration_in_minutes': 542, 'day': 2},
           {'date': '2022-09-08', 'duration_in_minutes': 496, 'day': 3},
           {'date': '2022-09-09', 'duration_in_minutes': 533, 'day': 4},
           {'date': '2022-09-10', 'duration_in_minutes': 520, 'day': 5},
           {'date': '2022-09-11', 'duration_in_minutes': 547, 'day': 6},
           {'date': '2022-09-12', 'duration_in_minutes': 614, 'day': 0},
           {'date': '2022-09-13', 'duration_in_minutes': 542, 'day': 1},
           {'date': '2022-09-14', 'duration_in_minutes': 546, 'day': 2},
           {'date': '2022-09-15', 'duration_in_minutes': 548, 'day': 3},
           {'date': '2022-09-16', 'duration_in_minutes': 546, 'day': 4},
           {'date': '2022-09-17', 'duration_in_minutes': 579, 'day': 5},
           {'date': '2022-09-18', 'duration_in_minutes': 594, 'day': 6},
           {'date': '2022-09-19', 'duration_in_minutes': 524, 'day': 0},
           {'date': '2022-09-20', 'duration_in_minutes': 561, 'day': 1},
           {'date': '2022-09-21', 'duration_in_minutes': 491, 'day': 2},
           {'date': '2022-09-22', 'duration_in_minutes': 531, 'day': 3},
           {'date': '2022-09-23', 'duration_in_minutes': 508, 'day': 4},
           {'date': '2022-09-24', 'duration_in_minutes': 543, 'day': 5},
           {'date': '2022-09-25', 'duration_in_minutes': 505, 'day': 6},
           {'date': '2022-09-26', 'duration_in_minutes': 544, 'day': 0},
           {'date': '2022-09-27', 'duration_in_minutes': 520, 'day': 1},
           {'date': '2022-09-28', 'duration_in_minutes': 481, 'day': 2},
           {'date': '2022-09-29', 'duration_in_minutes': 549, 'day': 3},
           {'date': '2022-09-30', 'duration_in_minutes': 628, 'day': 4},
           {'date': '2022-10-01', 'duration_in_minutes': 488, 'day': 5},
           {'date': '2022-10-02', 'duration_in_minutes': 589, 'day': 6},
           {'date': '2022-10-03', 'duration_in_minutes': 502, 'day': 0},
           {'date': '2022-10-04', 'duration_in_minutes': 481, 'day': 1},
           {'date': '2022-10-05', 'duration_in_minutes': 569, 'day': 2},
           {'date': '2022-10-06', 'duration_in_minutes': 578, 'day': 3},
           {'date': '2022-10-07', 'duration_in_minutes': 515, 'day': 4},
           {'date': '2022-10-08', 'duration_in_minutes': 498, 'day': 5},
           {'date': '2022-10-09', 'duration_in_minutes': 650, 'day': 6},
           {'date': '2022-10-10', 'duration_in_minutes': 547, 'day': 0},
           {'date': '2022-10-11', 'duration_in_minutes': 491, 'day': 1},
           {'date': '2022-10-12', 'duration_in_minutes': 511, 'day': 2},
           {'date': '2022-10-13', 'duration_in_minutes': 538, 'day': 3},
           {'date': '2022-10-14', 'duration_in_minutes': 495, 'day': 4},
           {'date': '2022-10-15', 'duration_in_minutes': 526, 'day': 5},
           {'date': '2022-10-16', 'duration_in_minutes': 505, 'day': 6},
           {'date': '2022-10-17', 'duration_in_minutes': 523, 'day': 0},
           {'date': '2022-10-18', 'duration_in_minutes': 595, 'day': 1},
           {'date': '2022-10-19', 'duration_in_minutes': 550, 'day': 2},
           {'date': '2022-10-20', 'duration_in_minutes': 493, 'day': 3},
           {'date': '2022-10-21', 'duration_in_minutes': 499, 'day': 4},
           {'date': '2022-10-22', 'duration_in_minutes': 604, 'day': 5},
           {'date': '2022-10-23', 'duration_in_minutes': 573, 'day': 6},
           {'date': '2022-10-24', 'duration_in_minutes': 567, 'day': 0},
           {'date': '2022-10-25', 'duration_in_minutes': 623, 'day': 1},
           {'date': '2022-10-26', 'duration_in_minutes': 584, 'day': 2},
           {'date': '2022-10-27', 'duration_in_minutes': 519, 'day': 3},
           {'date': '2022-10-28', 'duration_in_minutes': 597, 'day': 4},
           {'date': '2022-10-29', 'duration_in_minutes': 620, 'day': 5}]
logs = [{'date': '2022-08-30', 'start': '09:53', 'end': '12:10',
         'description': 'The sudden rainstorm washed crocodiles into the ocean.', 'duration_in_minutes': 137, 'day': 1},
        {'date': '2022-08-30', 'start': '13:07', 'end': '15:10',
         'description': 'Behind the window was a reflection that only instilled fear.', 'duration_in_minutes': 123,
         'day': 1}, {'date': '2022-08-30', 'start': '15:36', 'end': '18:04',
                     'description': "They're playing the piano while flying in the plane.", 'duration_in_minutes': 148,
                     'day': 1}, {'date': '2022-08-30', 'start': '18:50', 'end': '20:41',
                                 'description': 'The skeleton had skeletons of his own in the closet.',
                                 'duration_in_minutes': 111, 'day': 1},
        {'date': '2022-08-31', 'start': '08:19', 'end': '10:29', 'description': 'We need to rent a room for our party.',
         'duration_in_minutes': 130, 'day': 2}, {'date': '2022-08-31', 'start': '11:17', 'end': '13:48',
                                                 'description': 'The crowd yells and screams for more memes.',
                                                 'duration_in_minutes': 151, 'day': 2},
        {'date': '2022-08-31', 'start': '14:07', 'end': '16:33',
         'description': 'It was a really good Monday for being a Saturday.', 'duration_in_minutes': 146, 'day': 2},
        {'date': '2022-08-31', 'start': '17:07', 'end': '19:48',
         'description': 'He wondered if it could be called a beach if there was no sand.', 'duration_in_minutes': 161,
         'day': 2}, {'date': '2022-09-01', 'start': '09:13', 'end': '11:17',
                     'description': 'The ice-cream trucks bring back bad memories for all of us.',
                     'duration_in_minutes': 124, 'day': 3}, {'date': '2022-09-01', 'start': '12:00', 'end': '13:36',
                                                             'description': 'People who insist on picking their teeth with their elbows are so annoying!',
                                                             'duration_in_minutes': 96, 'day': 3},
        {'date': '2022-09-01', 'start': '14:27', 'end': '16:48',
         'description': 'The three-year-old girl ran down the beach as the kite flew behind her.',
         'duration_in_minutes': 141, 'day': 3}, {'date': '2022-09-01', 'start': '17:15', 'end': '19:50',
                                                 'description': 'He knew it was going to be a bad day when he saw mountain lions roaming the streets.',
                                                 'duration_in_minutes': 155, 'day': 3},
        {'date': '2022-09-02', 'start': '09:33', 'end': '11:48',
         'description': 'I cheated while playing the darts tournament by using a longbow.', 'duration_in_minutes': 135,
         'day': 4}, {'date': '2022-09-02', 'start': '12:30', 'end': '15:17',
                     'description': 'Today I dressed my unicorn in preparation for the race.',
                     'duration_in_minutes': 167, 'day': 4}, {'date': '2022-09-02', 'start': '15:44', 'end': '18:03',
                                                             'description': 'He found the end of the rainbow and was surprised at what he found there.',
                                                             'duration_in_minutes': 139, 'day': 4},
        {'date': '2022-09-02', 'start': '18:55', 'end': '21:26',
         'description': "She hadn't had her cup of coffee, and that made things all the worse.",
         'duration_in_minutes': 151, 'day': 4}, {'date': '2022-09-03', 'start': '09:35', 'end': '11:20',
                                                 'description': "Honestly, I didn't care much for the first season, so I didn't bother with the second.",
                                                 'duration_in_minutes': 105, 'day': 5},
        {'date': '2022-09-03', 'start': '12:10', 'end': '15:06',
         'description': 'She had that tint of craziness in her soul that made her believe she could actually make a difference.',
         'duration_in_minutes': 176, 'day': 5}, {'date': '2022-09-03', 'start': '15:48', 'end': '18:44',
                                                 'description': 'The swirled lollipop had issues with the pop rock candy.',
                                                 'duration_in_minutes': 176, 'day': 5},
        {'date': '2022-09-03', 'start': '19:15', 'end': '21:01',
         'description': 'I purchased a baby clown from the Russian terrorist black market.', 'duration_in_minutes': 106,
         'day': 5}, {'date': '2022-09-04', 'start': '09:46', 'end': '11:32',
                     'description': 'He learned the hardest lesson of his life and had the scars, both physical and mental, to prove it.',
                     'duration_in_minutes': 106, 'day': 6}, {'date': '2022-09-04', 'start': '12:10', 'end': '13:51',
                                                             'description': 'The secret code they created made no sense, even to them.',
                                                             'duration_in_minutes': 101, 'day': 6},
        {'date': '2022-09-04', 'start': '14:36', 'end': '17:02',
         'description': 'Twin 4-month-olds slept in the shade of the palm tree while the mother tanned in the sun.',
         'duration_in_minutes': 146, 'day': 6}, {'date': '2022-09-04', 'start': '17:16', 'end': '19:50',
                                                 'description': 'He never understood why what, when, and where left out who.',
                                                 'duration_in_minutes': 154, 'day': 6},
        {'date': '2022-09-05', 'start': '09:32', 'end': '11:34',
         'description': 'He told us a very exciting adventure story.', 'duration_in_minutes': 122, 'day': 0},
        {'date': '2022-09-05', 'start': '11:54', 'end': '13:45',
         'description': "It's difficult to understand the lengths he'd go to remain short.", 'duration_in_minutes': 111,
         'day': 0}, {'date': '2022-09-05', 'start': '14:41', 'end': '16:34',
                     'description': 'The manager of the fruit stand always sat and only sold vegetables.',
                     'duration_in_minutes': 113, 'day': 0}, {'date': '2022-09-05', 'start': '17:19', 'end': '19:05',
                                                             'description': 'The thunderous roar of the jet overhead confirmed her worst fears.',
                                                             'duration_in_minutes': 106, 'day': 0},
        {'date': '2022-09-05', 'start': '19:36', 'end': '22:27',
         'description': 'The trick to getting kids to eat anything is to put catchup on it.',
         'duration_in_minutes': 171, 'day': 0}, {'date': '2022-09-06', 'start': '09:36', 'end': '11:26',
                                                 'description': 'Nothing seemed out of place except the washing machine in the bar.',
                                                 'duration_in_minutes': 110, 'day': 1},
        {'date': '2022-09-06', 'start': '12:18', 'end': '15:01',
         'description': "It's not possible to convince a monkey to give you a banana by promising it infinite bananas when they die.",
         'duration_in_minutes': 163, 'day': 1}, {'date': '2022-09-06', 'start': '15:23', 'end': '18:09',
                                                 'description': 'They finished building the road they knew no one would ever use.',
                                                 'duration_in_minutes': 166, 'day': 1},
        {'date': '2022-09-06', 'start': '18:56', 'end': '21:44',
         'description': 'Malls are great places to shop; I can find everything I need under one roof.',
         'duration_in_minutes': 168, 'day': 1}, {'date': '2022-09-07', 'start': '08:28', 'end': '10:21',
                                                 'description': 'The manager of the fruit stand always sat and only sold vegetables.',
                                                 'duration_in_minutes': 113, 'day': 2},
        {'date': '2022-09-07', 'start': '11:04', 'end': '13:01',
         'description': 'He would only survive if he kept the fire going and he could hear thunder in the distance.',
         'duration_in_minutes': 117, 'day': 2}, {'date': '2022-09-07', 'start': '13:40', 'end': '16:15',
                                                 'description': 'The toddler’s endless tantrum caused the entire plane anxiety.',
                                                 'duration_in_minutes': 155, 'day': 2},
        {'date': '2022-09-07', 'start': '17:09', 'end': '19:46',
         'description': 'When confronted with a rotary dial phone the teenager was perplexed.',
         'duration_in_minutes': 157, 'day': 2},
        {'date': '2022-09-08', 'start': '09:17', 'end': '11:02', 'description': 'Tom got a small piece of pie.',
         'duration_in_minutes': 105, 'day': 3}, {'date': '2022-09-08', 'start': '11:54', 'end': '13:46',
                                                 'description': 'Buried deep in the snow, he hoped his batteries were fresh in his avalanche beacon.',
                                                 'duration_in_minutes': 112, 'day': 3},
        {'date': '2022-09-08', 'start': '14:07', 'end': '16:20',
         'description': "His confidence would have bee admirable if it wasn't for his stupidity.",
         'duration_in_minutes': 133, 'day': 3}, {'date': '2022-09-08', 'start': '17:17', 'end': '19:43',
                                                 'description': 'A quiet house is nice until you are ordered to stay in it for months.',
                                                 'duration_in_minutes': 146, 'day': 3},
        {'date': '2022-09-09', 'start': '09:11', 'end': '12:05',
         'description': 'Smoky the Bear secretly started the fires.', 'duration_in_minutes': 174, 'day': 4},
        {'date': '2022-09-09', 'start': '12:56', 'end': '14:34',
         'description': 'He was the type of guy who liked Christmas lights on his house in the middle of July.',
         'duration_in_minutes': 98, 'day': 4}, {'date': '2022-09-09', 'start': '15:07', 'end': '17:39',
                                                'description': 'She had that tint of craziness in her soul that made her believe she could actually make a difference.',
                                                'duration_in_minutes': 152, 'day': 4},
        {'date': '2022-09-09', 'start': '18:05', 'end': '19:54',
         'description': 'As you consider all the possible ways to improve yourself and the world, you notice John Travolta seems fairly unhappy.',
         'duration_in_minutes': 109, 'day': 4}, {'date': '2022-09-10', 'start': '08:06', 'end': '10:28',
                                                 'description': 'Sometimes I stare at a door or a wall and I wonder what is this reality, why am I alive, and what is this all about?',
                                                 'duration_in_minutes': 142, 'day': 5},
        {'date': '2022-09-10', 'start': '11:23', 'end': '12:54',
         'description': "He wasn't bitter that she had moved on but from the radish.", 'duration_in_minutes': 91,
         'day': 5}, {'date': '2022-09-10', 'start': '13:38', 'end': '15:50',
                     'description': 'Nobody has encountered an explosive daisy and lived to tell the tale.',
                     'duration_in_minutes': 132, 'day': 5}, {'date': '2022-09-10', 'start': '16:23', 'end': '18:58',
                                                             'description': 'Waffles are always better without fire ants and fleas.',
                                                             'duration_in_minutes': 155, 'day': 5},
        {'date': '2022-09-11', 'start': '09:37', 'end': '12:00',
         'description': 'Even though he thought the world was flat he didn’t see the irony of wanting to travel around the world.',
         'duration_in_minutes': 143, 'day': 6}, {'date': '2022-09-11', 'start': '12:26', 'end': '15:01',
                                                 'description': 'Nancy thought the best way to create a welcoming home was to line it with barbed wire.',
                                                 'duration_in_minutes': 155, 'day': 6},
        {'date': '2022-09-11', 'start': '15:13', 'end': '17:48',
         'description': 'Iron pyrite is the most foolish of all minerals.', 'duration_in_minutes': 155, 'day': 6},
        {'date': '2022-09-11', 'start': '18:26', 'end': '20:00',
         'description': 'The fox in the tophat whispered into the ear of the rabbit.', 'duration_in_minutes': 94,
         'day': 6}, {'date': '2022-09-12', 'start': '08:21', 'end': '10:21',
                     'description': 'Joyce enjoyed eating pancakes with ketchup.', 'duration_in_minutes': 120,
                     'day': 0}, {'date': '2022-09-12', 'start': '11:13', 'end': '13:01',
                                 'description': 'The swirled lollipop had issues with the pop rock candy.',
                                 'duration_in_minutes': 108, 'day': 0},
        {'date': '2022-09-12', 'start': '13:29', 'end': '15:00',
         'description': 'Poison ivy grew through the fence they said was impenetrable.', 'duration_in_minutes': 91,
         'day': 0}, {'date': '2022-09-12', 'start': '15:36', 'end': '18:08',
                     'description': 'At that moment she realized she had a sixth sense.', 'duration_in_minutes': 152,
                     'day': 0}, {'date': '2022-09-12', 'start': '19:07', 'end': '21:30',
                                 'description': "The bullet pierced the window shattering it before missing Danny's head by mere millimeters.",
                                 'duration_in_minutes': 143, 'day': 0},
        {'date': '2022-09-13', 'start': '09:39', 'end': '11:14',
         'description': 'When I was little I had a car door slammed shut on my hand and I still remember it quite vividly.',
         'duration_in_minutes': 95, 'day': 1}, {'date': '2022-09-13', 'start': '12:07', 'end': '14:50',
                                                'description': "She could hear him in the shower singing with a joy she hoped he'd retain after she delivered the news.",
                                                'duration_in_minutes': 163, 'day': 1},
        {'date': '2022-09-13', 'start': '15:49', 'end': '18:38',
         'description': 'It had been sixteen days since the zombies first attacked.', 'duration_in_minutes': 169,
         'day': 1}, {'date': '2022-09-13', 'start': '19:36', 'end': '21:31',
                     'description': 'The light that burns twice as bright burns half as long.',
                     'duration_in_minutes': 115, 'day': 1}, {'date': '2022-09-14', 'start': '09:08', 'end': '11:13',
                                                             'description': 'Malls are great places to shop; I can find everything I need under one roof.',
                                                             'duration_in_minutes': 125, 'day': 2},
        {'date': '2022-09-14', 'start': '11:30', 'end': '14:30',
         'description': "It's never been my responsibility to glaze the donuts.", 'duration_in_minutes': 180, 'day': 2},
        {'date': '2022-09-14', 'start': '15:23', 'end': '17:32',
         'description': "She wrote him a long letter, but he didn't read it.", 'duration_in_minutes': 129, 'day': 2},
        {'date': '2022-09-14', 'start': '18:18', 'end': '20:10',
         'description': 'Purple is the best city in the forest.', 'duration_in_minutes': 112, 'day': 2},
        {'date': '2022-09-15', 'start': '08:53', 'end': '10:45',
         'description': 'The random sentence generator generated a random sentence about a random sentence.',
         'duration_in_minutes': 112, 'day': 3}, {'date': '2022-09-15', 'start': '11:27', 'end': '14:00',
                                                 'description': 'Everybody should read Chaucer to improve their everyday vocabulary.',
                                                 'duration_in_minutes': 153, 'day': 3},
        {'date': '2022-09-15', 'start': '14:31', 'end': '16:28',
         'description': 'He would only survive if he kept the fire going and he could hear thunder in the distance.',
         'duration_in_minutes': 117, 'day': 3}, {'date': '2022-09-15', 'start': '16:43', 'end': '19:29',
                                                 'description': 'He enjoys practicing his ballet in the bathroom.',
                                                 'duration_in_minutes': 166, 'day': 3},
        {'date': '2022-09-16', 'start': '09:21', 'end': '11:36',
         'description': "There's a message for you if you look up.", 'duration_in_minutes': 135, 'day': 4},
        {'date': '2022-09-16', 'start': '11:55', 'end': '14:19',
         'description': 'Purple is the best city in the forest.', 'duration_in_minutes': 144, 'day': 4},
        {'date': '2022-09-16', 'start': '15:13', 'end': '17:13',
         'description': 'The old rusted farm equipment surrounded the house predicting its demise.',
         'duration_in_minutes': 120, 'day': 4}, {'date': '2022-09-16', 'start': '18:00', 'end': '20:27',
                                                 'description': 'She felt that chill that makes the hairs on the back of your neck when he walked into the room.',
                                                 'duration_in_minutes': 147, 'day': 4},
        {'date': '2022-09-17', 'start': '08:09', 'end': '10:29',
         'description': 'The blinking lights of the antenna tower came into focus just as I heard a loud snap.',
         'duration_in_minutes': 140, 'day': 5}, {'date': '2022-09-17', 'start': '11:19', 'end': '14:07',
                                                 'description': "If you don't like toenails, you probably shouldn't look at your feet.",
                                                 'duration_in_minutes': 168, 'day': 5},
        {'date': '2022-09-17', 'start': '14:18', 'end': '16:58',
         'description': 'The thick foliage and intertwined vines made the hike nearly impossible.',
         'duration_in_minutes': 160, 'day': 5}, {'date': '2022-09-17', 'start': '17:43', 'end': '19:34',
                                                 'description': "I made myself a peanut butter sandwich as I didn't want to subsist on veggie crackers.",
                                                 'duration_in_minutes': 111, 'day': 5},
        {'date': '2022-09-18', 'start': '09:04', 'end': '10:49',
         'description': 'The mysterious diary records the voice.', 'duration_in_minutes': 105, 'day': 6},
        {'date': '2022-09-18', 'start': '11:40', 'end': '14:07',
         'description': 'Giving directions that the mountains are to the west only works when you can see them.',
         'duration_in_minutes': 147, 'day': 6}, {'date': '2022-09-18', 'start': '14:18', 'end': '17:07',
                                                 'description': 'Jeanne wished she has chosen the red button.',
                                                 'duration_in_minutes': 169, 'day': 6},
        {'date': '2022-09-18', 'start': '17:54', 'end': '20:47', 'description': 'I am never at home on Sundays.',
         'duration_in_minutes': 173, 'day': 6}, {'date': '2022-09-19', 'start': '09:00', 'end': '10:33',
                                                 'description': 'He found his art never progressed when he literally used his sweat and tears.',
                                                 'duration_in_minutes': 93, 'day': 0},
        {'date': '2022-09-19', 'start': '11:12', 'end': '13:11',
         'description': 'As the asteroid hurtled toward earth, Becky was upset her dentist appointment had been canceled.',
         'duration_in_minutes': 119, 'day': 0}, {'date': '2022-09-19', 'start': '13:30', 'end': '16:14',
                                                 'description': 'Wisdom is easily acquired when hiding under the bed with a saucepan on your head.',
                                                 'duration_in_minutes': 164, 'day': 0},
        {'date': '2022-09-19', 'start': '16:58', 'end': '19:26',
         'description': 'Nothing is as cautiously cuddly as a pet porcupine.', 'duration_in_minutes': 148, 'day': 0},
        {'date': '2022-09-20', 'start': '08:37', 'end': '10:59',
         'description': 'Iron pyrite is the most foolish of all minerals.', 'duration_in_minutes': 142, 'day': 1},
        {'date': '2022-09-20', 'start': '11:46', 'end': '13:44',
         'description': 'The pet shop stocks everything you need to keep your anaconda happy.',
         'duration_in_minutes': 118, 'day': 1}, {'date': '2022-09-20', 'start': '14:06', 'end': '16:27',
                                                 'description': 'The underground bunker was filled with chips and candy.',
                                                 'duration_in_minutes': 141, 'day': 1},
        {'date': '2022-09-20', 'start': '16:41', 'end': '19:21',
         'description': 'Nancy was proud that she ran a tight shipwreck.', 'duration_in_minutes': 160, 'day': 1},
        {'date': '2022-09-21', 'start': '09:31', 'end': '11:15',
         'description': 'Joyce enjoyed eating pancakes with ketchup.', 'duration_in_minutes': 104, 'day': 2},
        {'date': '2022-09-21', 'start': '11:41', 'end': '13:50',
         'description': 'Before he moved to the inner city, he had always believed that security complexes were psychological.',
         'duration_in_minutes': 129, 'day': 2}, {'date': '2022-09-21', 'start': '14:34', 'end': '17:16',
                                                 'description': 'I am counting my calories, yet I really want dessert.',
                                                 'duration_in_minutes': 162, 'day': 2},
        {'date': '2022-09-21', 'start': '17:29', 'end': '19:05',
         'description': "Although it wasn't a pot of gold, Nancy was still enthralled at what she found at the end of the rainbow.",
         'duration_in_minutes': 96, 'day': 2}, {'date': '2022-09-22', 'start': '08:20', 'end': '10:47',
                                                'description': "Dolores wouldn't have eaten the meal if she had known what it actually was.",
                                                'duration_in_minutes': 147, 'day': 3},
        {'date': '2022-09-22', 'start': '11:06', 'end': '12:36',
         'description': 'The tour bus was packed with teenage girls heading toward their next adventure.',
         'duration_in_minutes': 90, 'day': 3}, {'date': '2022-09-22', 'start': '13:05', 'end': '15:52',
                                                'description': 'They did nothing as the raccoon attacked the lady’s bag of food.',
                                                'duration_in_minutes': 167, 'day': 3},
        {'date': '2022-09-22', 'start': '16:21', 'end': '18:28',
         'description': 'He learned the hardest lesson of his life and had the scars, both physical and mental, to prove it.',
         'duration_in_minutes': 127, 'day': 3}, {'date': '2022-09-23', 'start': '08:33', 'end': '10:27',
                                                 'description': 'The blinking lights of the antenna tower came into focus just as I heard a loud snap.',
                                                 'duration_in_minutes': 114, 'day': 4},
        {'date': '2022-09-23', 'start': '11:11', 'end': '13:02',
         'description': 'Beach-combing replaced wine tasting as his new obsession.', 'duration_in_minutes': 111,
         'day': 4}, {'date': '2022-09-23', 'start': '13:46', 'end': '16:08',
                     'description': 'Flying fish flew by the space station.', 'duration_in_minutes': 142, 'day': 4},
        {'date': '2022-09-23', 'start': '17:07', 'end': '19:28', 'description': 'With the high wind warning',
         'duration_in_minutes': 141, 'day': 4}, {'date': '2022-09-24', 'start': '09:55', 'end': '12:55',
                                                 'description': "If you spin around three times, you'll start to feel melancholy.",
                                                 'duration_in_minutes': 180, 'day': 5},
        {'date': '2022-09-24', 'start': '13:30', 'end': '15:38',
         'description': 'Shakespeare was a famous 17th-century diesel mechanic.', 'duration_in_minutes': 128, 'day': 5},
        {'date': '2022-09-24', 'start': '16:34', 'end': '18:56',
         'description': 'For oil spots on the floor, nothing beats parking a motorbike in the lounge.',
         'duration_in_minutes': 142, 'day': 5}, {'date': '2022-09-24', 'start': '19:32', 'end': '21:05',
                                                 'description': "The bullet pierced the window shattering it before missing Danny's head by mere millimeters.",
                                                 'duration_in_minutes': 93, 'day': 5},
        {'date': '2022-09-25', 'start': '08:13', 'end': '09:43',
         'description': 'Lucifer was surprised at the amount of life at Death Valley.', 'duration_in_minutes': 90,
         'day': 6}, {'date': '2022-09-25', 'start': '10:10', 'end': '13:10', 'description': 'Love is not like pizza.',
                     'duration_in_minutes': 180, 'day': 6}, {'date': '2022-09-25', 'start': '13:31', 'end': '15:38',
                                                             'description': "The irony of the situation wasn't lost on anyone in the room.",
                                                             'duration_in_minutes': 127, 'day': 6},
        {'date': '2022-09-25', 'start': '16:28', 'end': '18:16',
         'description': "The sight of his goatee made me want to run and hide under my sister-in-law's bed.",
         'duration_in_minutes': 108, 'day': 6}, {'date': '2022-09-26', 'start': '08:30', 'end': '10:02',
                                                 'description': 'Twin 4-month-olds slept in the shade of the palm tree while the mother tanned in the sun.',
                                                 'duration_in_minutes': 92, 'day': 0},
        {'date': '2022-09-26', 'start': '10:43', 'end': '12:54',
         'description': 'The blue parrot drove by the hitchhiking mongoose.', 'duration_in_minutes': 131, 'day': 0},
        {'date': '2022-09-26', 'start': '13:15', 'end': '15:51',
         'description': 'I think I will buy the red car, or I will lease the blue one.', 'duration_in_minutes': 156,
         'day': 0}, {'date': '2022-09-26', 'start': '16:23', 'end': '19:08',
                     'description': 'I was offended by the suggestion that my baby brother was a jewel thief.',
                     'duration_in_minutes': 165, 'day': 0}, {'date': '2022-09-27', 'start': '09:05', 'end': '11:33',
                                                             'description': 'We have young kids who often walk into our room at night for various reasons including clowns in the closet.',
                                                             'duration_in_minutes': 148, 'day': 1},
        {'date': '2022-09-27', 'start': '12:21', 'end': '13:53', 'description': 'Pink horses galloped across the sea.',
         'duration_in_minutes': 92, 'day': 1}, {'date': '2022-09-27', 'start': '14:17', 'end': '16:11',
                                                'description': "Dolores wouldn't have eaten the meal if she had known what it actually was.",
                                                'duration_in_minutes': 114, 'day': 1},
        {'date': '2022-09-27', 'start': '16:33', 'end': '19:19', 'description': 'This is a Japanese doll.',
         'duration_in_minutes': 166, 'day': 1}, {'date': '2022-09-28', 'start': '09:51', 'end': '12:08',
                                                 'description': "Strawberries must be the one food that doesn't go well with this brand of paint.",
                                                 'duration_in_minutes': 137, 'day': 2},
        {'date': '2022-09-28', 'start': '12:22', 'end': '14:56',
         'description': 'The hand sanitizer was actually clear glue.', 'duration_in_minutes': 154, 'day': 2},
        {'date': '2022-09-28', 'start': '15:16', 'end': '16:52', 'description': 'In that instant, everything changed.',
         'duration_in_minutes': 96, 'day': 2},
        {'date': '2022-09-28', 'start': '17:03', 'end': '18:37', 'description': 'Let me help you with your baggage.',
         'duration_in_minutes': 94, 'day': 2}, {'date': '2022-09-29', 'start': '09:10', 'end': '11:34',
                                                'description': 'David proudly graduated from high school top of his class at age 97.',
                                                'duration_in_minutes': 144, 'day': 3},
        {'date': '2022-09-29', 'start': '12:25', 'end': '14:05',
         'description': 'Peter found road kill an excellent way to save money on dinner.', 'duration_in_minutes': 100,
         'day': 3}, {'date': '2022-09-29', 'start': '15:01', 'end': '18:00',
                     'description': "The body piercing didn't go exactly as he expected.", 'duration_in_minutes': 179,
                     'day': 3}, {'date': '2022-09-29', 'start': '18:11', 'end': '20:17',
                                 'description': 'When he asked her favorite number, she answered without hesitation that it was diamonds.',
                                 'duration_in_minutes': 126, 'day': 3},
        {'date': '2022-09-30', 'start': '08:41', 'end': '11:25',
         'description': 'The glacier came alive as the climbers hiked closer.', 'duration_in_minutes': 164, 'day': 4},
        {'date': '2022-09-30', 'start': '12:08', 'end': '14:08',
         'description': 'The swirled lollipop had issues with the pop rock candy.', 'duration_in_minutes': 120,
         'day': 4}, {'date': '2022-09-30', 'start': '14:54', 'end': '17:39',
                     'description': 'The pigs were insulted that they were named hamburgers.',
                     'duration_in_minutes': 165, 'day': 4}, {'date': '2022-09-30', 'start': '18:22', 'end': '21:21',
                                                             'description': "There's a growing trend among teenagers of using frisbees as go-cart wheels.",
                                                             'duration_in_minutes': 179, 'day': 4},
        {'date': '2022-10-01', 'start': '08:18', 'end': '10:14',
         'description': "Please put on these earmuffs because I can't you hear.", 'duration_in_minutes': 116, 'day': 5},
        {'date': '2022-10-01', 'start': '10:32', 'end': '12:53',
         'description': 'Each person who knows you has a different perception of who you are.',
         'duration_in_minutes': 141, 'day': 5}, {'date': '2022-10-01', 'start': '13:24', 'end': '15:16',
                                                 'description': 'He poured rocks in the dungeon of his mind.',
                                                 'duration_in_minutes': 112, 'day': 5},
        {'date': '2022-10-01', 'start': '15:45', 'end': '17:44',
         'description': 'Purple is the best city in the forest.', 'duration_in_minutes': 119, 'day': 5},
        {'date': '2022-10-02', 'start': '08:34', 'end': '10:20',
         'description': 'It was always dangerous to drive with him since he insisted the safety cones were a slalom course.',
         'duration_in_minutes': 106, 'day': 6}, {'date': '2022-10-02', 'start': '10:39', 'end': '13:18',
                                                 'description': 'She was the type of girl that always burnt sugar to show she cared.',
                                                 'duration_in_minutes': 159, 'day': 6},
        {'date': '2022-10-02', 'start': '13:43', 'end': '16:20',
         'description': 'The waitress was not amused when he ordered green eggs and ham.', 'duration_in_minutes': 157,
         'day': 6}, {'date': '2022-10-02', 'start': '16:48', 'end': '19:35',
                     'description': "Gary didn't understand why Doug went upstairs to get one dollar bills when he invited him to go cow tipping.",
                     'duration_in_minutes': 167, 'day': 6},
        {'date': '2022-10-03', 'start': '09:31', 'end': '11:54', 'description': 'Mary plays the piano.',
         'duration_in_minutes': 143, 'day': 0}, {'date': '2022-10-03', 'start': '12:17', 'end': '14:40',
                                                 'description': 'The urgent care center was flooded with patients after the news of a new deadly virus was made public.',
                                                 'duration_in_minutes': 143, 'day': 0},
        {'date': '2022-10-03', 'start': '15:09', 'end': '16:40',
         'description': 'The gruff old man sat in the back of the bait shop grumbling to himself as he scooped out a handful of worms.',
         'duration_in_minutes': 91, 'day': 0}, {'date': '2022-10-03', 'start': '17:35', 'end': '19:40',
                                                'description': "For some unfathomable reason, the response team didn't consider a lack of milk for my cereal as a proper emergency.",
                                                'duration_in_minutes': 125, 'day': 0},
        {'date': '2022-10-04', 'start': '08:06', 'end': '10:03',
         'description': "I used to live in my neighbor's fishpond, but the aesthetic wasn't to my taste.",
         'duration_in_minutes': 117, 'day': 1}, {'date': '2022-10-04', 'start': '10:16', 'end': '12:51',
                                                 'description': "Standing on one's head at job interviews forms a lasting impression.",
                                                 'duration_in_minutes': 155, 'day': 1},
        {'date': '2022-10-04', 'start': '13:24', 'end': '15:14',
         'description': 'The sign said there was road work ahead so he decided to speed up.',
         'duration_in_minutes': 110, 'day': 1}, {'date': '2022-10-04', 'start': '15:29', 'end': '17:08',
                                                 'description': 'Malls are great places to shop; I can find everything I need under one roof.',
                                                 'duration_in_minutes': 99, 'day': 1},
        {'date': '2022-10-05', 'start': '08:47', 'end': '10:17',
         'description': "There should have been a time and a place, but this wasn't it.", 'duration_in_minutes': 90,
         'day': 2}, {'date': '2022-10-05', 'start': '10:46', 'end': '13:05',
                     'description': 'Her life in the confines of the house became her new normal.',
                     'duration_in_minutes': 139, 'day': 2}, {'date': '2022-10-05', 'start': '13:40', 'end': '16:37',
                                                             'description': 'He wondered if she would appreciate his toenail collection.',
                                                             'duration_in_minutes': 177, 'day': 2},
        {'date': '2022-10-05', 'start': '16:48', 'end': '19:31',
         'description': 'The secret ingredient to his wonderful life was crime.', 'duration_in_minutes': 163, 'day': 2},
        {'date': '2022-10-06', 'start': '08:11', 'end': '10:42',
         'description': 'I don’t respect anybody who can’t tell the difference between Pepsi and Coke.',
         'duration_in_minutes': 151, 'day': 3}, {'date': '2022-10-06', 'start': '11:38', 'end': '14:18',
                                                 'description': 'When nobody is around, the trees gossip about the people who have walked under them.',
                                                 'duration_in_minutes': 160, 'day': 3},
        {'date': '2022-10-06', 'start': '15:14', 'end': '17:36',
         'description': "It must be easy to commit crimes as a snake because you don't have to worry about leaving fingerprints.",
         'duration_in_minutes': 142, 'day': 3}, {'date': '2022-10-06', 'start': '18:36', 'end': '20:41',
                                                 'description': 'The fence was confused about whether it was supposed to keep things in or keep things out.',
                                                 'duration_in_minutes': 125, 'day': 3},
        {'date': '2022-10-07', 'start': '08:59', 'end': '11:11',
         'description': 'The gruff old man sat in the back of the bait shop grumbling to himself as he scooped out a handful of worms.',
         'duration_in_minutes': 132, 'day': 4}, {'date': '2022-10-07', 'start': '11:35', 'end': '13:21',
                                                 'description': "The hummingbird's wings blurred while it eagerly sipped the sugar water from the feeder.",
                                                 'duration_in_minutes': 106, 'day': 4},
        {'date': '2022-10-07', 'start': '14:03', 'end': '16:22', 'description': 'Hit me with your pet shark!',
         'duration_in_minutes': 139, 'day': 4}, {'date': '2022-10-07', 'start': '17:00', 'end': '19:18',
                                                 'description': 'The water flowing down the river didn’t look that powerful from the car',
                                                 'duration_in_minutes': 138, 'day': 4},
        {'date': '2022-10-08', 'start': '08:39', 'end': '11:28',
         'description': 'The delicious aroma from the kitchen was ruined by cigarette smoke.',
         'duration_in_minutes': 169, 'day': 5}, {'date': '2022-10-08', 'start': '12:10', 'end': '14:53',
                                                 'description': "There should have been a time and a place, but this wasn't it.",
                                                 'duration_in_minutes': 163, 'day': 5},
        {'date': '2022-10-08', 'start': '15:39', 'end': '18:25',
         'description': 'Chocolate covered crickets were his favorite snack.', 'duration_in_minutes': 166, 'day': 5},
        {'date': '2022-10-09', 'start': '08:27', 'end': '10:21',
         'description': 'Twin 4-month-olds slept in the shade of the palm tree while the mother tanned in the sun.',
         'duration_in_minutes': 114, 'day': 6}, {'date': '2022-10-09', 'start': '11:20', 'end': '13:44',
                                                 'description': "Yeah, I think it's a good environment for learning English.",
                                                 'duration_in_minutes': 144, 'day': 6},
        {'date': '2022-10-09', 'start': '14:27', 'end': '16:26',
         'description': "The llama couldn't resist trying the lemonade.", 'duration_in_minutes': 119, 'day': 6},
        {'date': '2022-10-09', 'start': '17:09', 'end': '18:44',
         'description': 'I only enjoy window shopping when the windows are transparent.', 'duration_in_minutes': 95,
         'day': 6}, {'date': '2022-10-09', 'start': '19:04', 'end': '22:02',
                     'description': 'I was fishing for compliments and accidentally caught a trout.',
                     'duration_in_minutes': 178, 'day': 6}, {'date': '2022-10-10', 'start': '08:26', 'end': '10:48',
                                                             'description': 'Potato wedges probably are not best for relationships.',
                                                             'duration_in_minutes': 142, 'day': 0},
        {'date': '2022-10-10', 'start': '11:48', 'end': '13:35',
         'description': 'Grape jelly was leaking out the hole in the roof.', 'duration_in_minutes': 107, 'day': 0},
        {'date': '2022-10-10', 'start': '13:55', 'end': '16:04', 'description': 'This is a Japanese doll.',
         'duration_in_minutes': 129, 'day': 0}, {'date': '2022-10-10', 'start': '16:41', 'end': '19:30',
                                                 'description': 'She found it strange that people use their cellphones to actually talk to one another.',
                                                 'duration_in_minutes': 169, 'day': 0},
        {'date': '2022-10-11', 'start': '08:45', 'end': '11:35',
         'description': 'She let the balloon float up into the air with her hopes and dreams.',
         'duration_in_minutes': 170, 'day': 1},
        {'date': '2022-10-11', 'start': '11:57', 'end': '14:24', 'description': 'I covered my friend in baby oil.',
         'duration_in_minutes': 147, 'day': 1}, {'date': '2022-10-11', 'start': '15:18', 'end': '18:12',
                                                 'description': 'Twin 4-month-olds slept in the shade of the palm tree while the mother tanned in the sun.',
                                                 'duration_in_minutes': 174, 'day': 1},
        {'date': '2022-10-12', 'start': '08:55', 'end': '10:31',
         'description': 'My dentist tells me that chewing bricks is very bad for your teeth.',
         'duration_in_minutes': 96, 'day': 2}, {'date': '2022-10-12', 'start': '11:10', 'end': '13:44',
                                                'description': 'The opportunity of a lifetime passed before him as he tried to decide between a cone or a cup.',
                                                'duration_in_minutes': 154, 'day': 2},
        {'date': '2022-10-12', 'start': '14:26', 'end': '16:34',
         'description': 'All you need to do is pick up the pen and begin.', 'duration_in_minutes': 128, 'day': 2},
        {'date': '2022-10-12', 'start': '17:31', 'end': '19:44',
         'description': 'The two walked down the slot canyon oblivious to the sound of thunder in the distance.',
         'duration_in_minutes': 133, 'day': 2}, {'date': '2022-10-13', 'start': '09:08', 'end': '11:14',
                                                 'description': 'Greetings from the galaxy MACS0647-JD, or what we call home.',
                                                 'duration_in_minutes': 126, 'day': 3},
        {'date': '2022-10-13', 'start': '11:46', 'end': '14:31', 'description': 'The shooter says goodbye to his love.',
         'duration_in_minutes': 165, 'day': 3}, {'date': '2022-10-13', 'start': '14:59', 'end': '17:19',
                                                 'description': 'She saw no irony asking me to change but wanting me to accept her for who she is.',
                                                 'duration_in_minutes': 140, 'day': 3},
        {'date': '2022-10-13', 'start': '17:52', 'end': '19:39',
         'description': 'He wondered why at 18 he was old enough to go to war, but not old enough to buy cigarettes.',
         'duration_in_minutes': 107, 'day': 3}, {'date': '2022-10-14', 'start': '08:46', 'end': '10:58',
                                                 'description': 'He said he was not there yesterday; however, many people saw him there.',
                                                 'duration_in_minutes': 132, 'day': 4},
        {'date': '2022-10-14', 'start': '11:31', 'end': '13:10',
         'description': 'He had concluded that pigs must be able to fly in Hog Heaven.', 'duration_in_minutes': 99,
         'day': 4}, {'date': '2022-10-14', 'start': '14:01', 'end': '16:41',
                     'description': 'While all her friends were positive that Mary had a sixth sense, she knew she actually had a seventh sense.',
                     'duration_in_minutes': 160, 'day': 4}, {'date': '2022-10-14', 'start': '16:52', 'end': '18:36',
                                                             'description': "There's probably enough glass in my cupboard to build an undersea aquarium.",
                                                             'duration_in_minutes': 104, 'day': 4},
        {'date': '2022-10-15', 'start': '08:11', 'end': '10:38',
         'description': "Peanuts don't grow on trees, but cashews do.", 'duration_in_minutes': 147, 'day': 5},
        {'date': '2022-10-15', 'start': '11:01', 'end': '12:58',
         'description': 'They desperately needed another drummer since the current one only knew how to play bongos.',
         'duration_in_minutes': 117, 'day': 5}, {'date': '2022-10-15', 'start': '13:26', 'end': '16:02',
                                                 'description': 'Truth in advertising and dinosaurs with skateboards have much in common.',
                                                 'duration_in_minutes': 156, 'day': 5},
        {'date': '2022-10-15', 'start': '16:17', 'end': '18:03',
         'description': 'Situps are a terrible way to end your day.', 'duration_in_minutes': 106, 'day': 5},
        {'date': '2022-10-16', 'start': '09:37', 'end': '11:30',
         'description': 'Joe discovered that traffic cones make excellent megaphones.', 'duration_in_minutes': 113,
         'day': 6}, {'date': '2022-10-16', 'start': '12:02', 'end': '14:31',
                     'description': 'Everyone says they love nature until they realize how dangerous she can be.',
                     'duration_in_minutes': 149, 'day': 6}, {'date': '2022-10-16', 'start': '15:04', 'end': '16:36',
                                                             'description': "There's no reason a hula hoop can't also be a circus ring.",
                                                             'duration_in_minutes': 92, 'day': 6},
        {'date': '2022-10-16', 'start': '17:06', 'end': '19:37',
         'description': 'Cats are good pets, for they are clean and are not noisy.', 'duration_in_minutes': 151,
         'day': 6}, {'date': '2022-10-17', 'start': '08:28', 'end': '10:50',
                     'description': 'My biggest joy is roasting almonds while stalking prey.',
                     'duration_in_minutes': 142, 'day': 0}, {'date': '2022-10-17', 'start': '11:08', 'end': '12:49',
                                                             'description': 'The pigs were insulted that they were named hamburgers.',
                                                             'duration_in_minutes': 101, 'day': 0},
        {'date': '2022-10-17', 'start': '13:31', 'end': '16:19',
         'description': 'He took one look at what was under the table and noped the hell out of there.',
         'duration_in_minutes': 168, 'day': 0}, {'date': '2022-10-17', 'start': '16:34', 'end': '18:26',
                                                 'description': "It's not possible to convince a monkey to give you a banana by promising it infinite bananas when they die.",
                                                 'duration_in_minutes': 112, 'day': 0},
        {'date': '2022-10-18', 'start': '08:24', 'end': '10:50',
         'description': 'The skeleton had skeletons of his own in the closet.', 'duration_in_minutes': 146, 'day': 1},
        {'date': '2022-10-18', 'start': '11:34', 'end': '14:17', 'description': 'Please wait outside of the house.',
         'duration_in_minutes': 163, 'day': 1}, {'date': '2022-10-18', 'start': '15:06', 'end': '17:17',
                                                 'description': 'All she wanted was the answer, but she had no idea how much she would hate it.',
                                                 'duration_in_minutes': 131, 'day': 1},
        {'date': '2022-10-18', 'start': '17:31', 'end': '20:06',
         'description': "He ended up burning his fingers poking someone else's fire.", 'duration_in_minutes': 155,
         'day': 1}, {'date': '2022-10-19', 'start': '09:33', 'end': '11:27',
                     'description': 'Someone I know recently combined Maple Syrup & buttered Popcorn thinking it would taste like caramel popcorn. It didn’t and they don’t recommend anyone else do it either.',
                     'duration_in_minutes': 114, 'day': 2}, {'date': '2022-10-19', 'start': '12:26', 'end': '14:06',
                                                             'description': 'This made him feel like an old-style rootbeer float smells.',
                                                             'duration_in_minutes': 100, 'day': 2},
        {'date': '2022-10-19', 'start': '14:31', 'end': '16:24',
         'description': 'He strives to keep the best lawn in the neighborhood.', 'duration_in_minutes': 113, 'day': 2},
        {'date': '2022-10-19', 'start': '17:07', 'end': '18:41',
         'description': "His confidence would have bee admirable if it wasn't for his stupidity.",
         'duration_in_minutes': 94, 'day': 2}, {'date': '2022-10-19', 'start': '19:01', 'end': '21:10',
                                                'description': 'Everybody should read Chaucer to improve their everyday vocabulary.',
                                                'duration_in_minutes': 129, 'day': 2},
        {'date': '2022-10-20', 'start': '09:51', 'end': '12:29',
         'description': 'I was fishing for compliments and accidentally caught a trout.', 'duration_in_minutes': 158,
         'day': 3}, {'date': '2022-10-20', 'start': '13:10', 'end': '15:58',
                     'description': 'I caught my squirrel rustling through my gym bag.', 'duration_in_minutes': 168,
                     'day': 3}, {'date': '2022-10-20', 'start': '16:32', 'end': '19:19',
                                 'description': "You have every right to be angry, but that doesn't give you the right to be mean.",
                                 'duration_in_minutes': 167, 'day': 3},
        {'date': '2022-10-21', 'start': '09:08', 'end': '11:39',
         'description': 'At that moment I was the most fearsome weasel in the entire swamp.',
         'duration_in_minutes': 151, 'day': 4}, {'date': '2022-10-21', 'start': '12:01', 'end': '14:28',
                                                 'description': 'It took him a while to realize that everything he decided not to change, he was actually choosing.',
                                                 'duration_in_minutes': 147, 'day': 4},
        {'date': '2022-10-21', 'start': '15:16', 'end': '17:06',
         'description': 'The waves were crashing on the shore; it was a lovely sight.', 'duration_in_minutes': 110,
         'day': 4}, {'date': '2022-10-21', 'start': '18:05', 'end': '19:36',
                     'description': 'The shark-infested South Pine channel was the only way in or out.',
                     'duration_in_minutes': 91, 'day': 4}, {'date': '2022-10-22', 'start': '08:35', 'end': '11:26',
                                                            'description': 'He learned the hardest lesson of his life and had the scars, both physical and mental, to prove it.',
                                                            'duration_in_minutes': 171, 'day': 5},
        {'date': '2022-10-22', 'start': '11:53', 'end': '14:36',
         'description': 'Charles ate the french fries knowing they would be his last meal.', 'duration_in_minutes': 163,
         'day': 5}, {'date': '2022-10-22', 'start': '15:10', 'end': '17:03',
                     'description': 'The urgent care center was flooded with patients after the news of a new deadly virus was made public.',
                     'duration_in_minutes': 113, 'day': 5}, {'date': '2022-10-22', 'start': '17:29', 'end': '20:06',
                                                             'description': "Written warnings in instruction manuals are worthless since rabbits can't read.",
                                                             'duration_in_minutes': 157, 'day': 5},
        {'date': '2022-10-23', 'start': '08:55', 'end': '10:55',
         'description': 'Sometimes you have to just give up and win by cheating.', 'duration_in_minutes': 120,
         'day': 6}, {'date': '2022-10-23', 'start': '11:46', 'end': '13:43',
                     'description': 'She wore green lipstick like a fashion icon.', 'duration_in_minutes': 117,
                     'day': 6}, {'date': '2022-10-23', 'start': '13:54', 'end': '15:28',
                                 'description': 'I checked to make sure that he was still alive.',
                                 'duration_in_minutes': 94, 'day': 6},
        {'date': '2022-10-23', 'start': '15:45', 'end': '18:04',
         'description': 'Grape jelly was leaking out the hole in the roof.', 'duration_in_minutes': 139, 'day': 6},
        {'date': '2022-10-23', 'start': '18:31', 'end': '20:14',
         'description': 'Barking dogs and screaming toddlers have the unique ability to turn friendly neighbors into cranky enemies.',
         'duration_in_minutes': 103, 'day': 6}, {'date': '2022-10-24', 'start': '08:01', 'end': '09:42',
                                                 'description': 'Everybody should read Chaucer to improve their everyday vocabulary.',
                                                 'duration_in_minutes': 101, 'day': 0},
        {'date': '2022-10-24', 'start': '10:26', 'end': '13:07',
         'description': 'Joe discovered that traffic cones make excellent megaphones.', 'duration_in_minutes': 161,
         'day': 0}, {'date': '2022-10-24', 'start': '13:22', 'end': '16:10',
                     'description': 'As the years pass by, we all know owners look more and more like their dogs.',
                     'duration_in_minutes': 168, 'day': 0}, {'date': '2022-10-24', 'start': '17:07', 'end': '19:24',
                                                             'description': 'A kangaroo is really just a rabbit on steroids.',
                                                             'duration_in_minutes': 137, 'day': 0},
        {'date': '2022-10-25', 'start': '09:44', 'end': '12:04',
         'description': 'The fox in the tophat whispered into the ear of the rabbit.', 'duration_in_minutes': 140,
         'day': 1}, {'date': '2022-10-25', 'start': '12:21', 'end': '14:30',
                     'description': "He's in a boy band which doesn't make much sense for a snake.",
                     'duration_in_minutes': 129, 'day': 1}, {'date': '2022-10-25', 'start': '14:49', 'end': '17:45',
                                                             'description': 'Smoky the Bear secretly started the fires.',
                                                             'duration_in_minutes': 176, 'day': 1},
        {'date': '2022-10-25', 'start': '18:36', 'end': '21:34',
         'description': 'He strives to keep the best lawn in the neighborhood.', 'duration_in_minutes': 178, 'day': 1},
        {'date': '2022-10-26', 'start': '08:18', 'end': '10:13', 'description': 'Let me help you with your baggage.',
         'duration_in_minutes': 115, 'day': 2}, {'date': '2022-10-26', 'start': '10:54', 'end': '13:52',
                                                 'description': 'The beach was crowded with snow leopards.',
                                                 'duration_in_minutes': 178, 'day': 2},
        {'date': '2022-10-26', 'start': '14:23', 'end': '17:07',
         'description': 'He felt that dining on the bridge brought romance to his relationship with his cat.',
         'duration_in_minutes': 164, 'day': 2},
        {'date': '2022-10-26', 'start': '17:47', 'end': '19:54', 'description': 'She did her best to help him.',
         'duration_in_minutes': 127, 'day': 2}, {'date': '2022-10-27', 'start': '09:37', 'end': '11:37',
                                                 'description': "Strawberries must be the one food that doesn't go well with this brand of paint.",
                                                 'duration_in_minutes': 120, 'day': 3},
        {'date': '2022-10-27', 'start': '12:05', 'end': '14:45', 'description': 'Tom got a small piece of pie.',
         'duration_in_minutes': 160, 'day': 3}, {'date': '2022-10-27', 'start': '15:25', 'end': '17:23',
                                                 'description': 'When he asked her favorite number, she answered without hesitation that it was diamonds.',
                                                 'duration_in_minutes': 118, 'day': 3},
        {'date': '2022-10-27', 'start': '17:36', 'end': '19:37',
         'description': 'There is no better feeling than staring at a wall with closed eyes.',
         'duration_in_minutes': 121, 'day': 3}, {'date': '2022-10-28', 'start': '08:46', 'end': '11:19',
                                                 'description': 'He realized there had been several deaths on this road, but his concern rose when he saw the exact number.',
                                                 'duration_in_minutes': 153, 'day': 4},
        {'date': '2022-10-28', 'start': '12:19', 'end': '14:59',
         'description': 'Italy is my favorite country; in fact, I plan to spend two weeks there next year.',
         'duration_in_minutes': 160, 'day': 4}, {'date': '2022-10-28', 'start': '15:55', 'end': '18:28',
                                                 'description': 'He fumbled in the darkness looking for the light switch, but when he finally found it there was someone already there.',
                                                 'duration_in_minutes': 153, 'day': 4},
        {'date': '2022-10-28', 'start': '18:49', 'end': '21:00',
         'description': 'He was surprised that his immense laziness was inspirational to others.',
         'duration_in_minutes': 131, 'day': 4},
        {'date': '2022-10-29', 'start': '09:51', 'end': '12:34', 'description': 'We need to rent a room for our party.',
         'duration_in_minutes': 163, 'day': 5}, {'date': '2022-10-29', 'start': '12:53', 'end': '14:34',
                                                 'description': 'The gloves protect my feet from excess work.',
                                                 'duration_in_minutes': 101, 'day': 5},
        {'date': '2022-10-29', 'start': '15:04', 'end': '18:02',
         'description': 'Thirty years later, she still thought it was okay to put the toilet paper roll under rather than over.',
         'duration_in_minutes': 178, 'day': 5}, {'date': '2022-10-29', 'start': '19:00', 'end': '21:58',
                                                 'description': 'She had that tint of craziness in her soul that made her believe she could actually make a difference.',
                                                 'duration_in_minutes': 178, 'day': 5}]


class TimeLoggerViewSet(viewsets.ModelViewSet):
    serializer_class = TimeLoggerSerializer
    permission_classes = [permissions.IsAuthenticated]
    filter_backends = [django_filters.rest_framework.DjangoFilterBackend, filters.SearchFilter]
    filterset_fields = ['date']
    search_fields = ['description']

    # queryset = TimeLog.objects.all()

    # def filter_queryset(self, queryset):
    #     pass

    def get_queryset(self):
        return TimeLog.objects.filter(user=self.request.user)

    def create(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        instance = serializer.save(user=request.user)
        return Response(self.serializer_class(instance).data)

    def list(self, request, *args, **kwargs):
        start_date = request.GET.get('start_date')
        if start_date:
            # logs = []
            # summary = [{'date': '2022-08-30', 'duration': 519, 'day': 1}, {'date': '2022-08-31', 'duration': 588, 'day': 2}, {'date': '2022-09-01', 'duration': 516, 'day': 3}, {'date': '2022-09-02', 'duration': 592, 'day': 4}, {'date': '2022-09-03', 'duration': 563, 'day': 5}, {'date': '2022-09-04', 'duration': 507, 'day': 6}, {'date': '2022-09-05', 'duration': 623, 'day': 0}, {'date': '2022-09-06', 'duration': 607, 'day': 1}, {'date': '2022-09-07', 'duration': 542, 'day': 2}, {'date': '2022-09-08', 'duration': 496, 'day': 3}, {'date': '2022-09-09', 'duration': 533, 'day': 4}, {'date': '2022-09-10', 'duration': 520, 'day': 5}, {'date': '2022-09-11', 'duration': 547, 'day': 6}, {'date': '2022-09-12', 'duration': 614, 'day': 0}, {'date': '2022-09-13', 'duration': 542, 'day': 1}, {'date': '2022-09-14', 'duration': 546, 'day': 2}, {'date': '2022-09-15', 'duration': 548, 'day': 3}, {'date': '2022-09-16', 'duration': 546, 'day': 4}, {'date': '2022-09-17', 'duration': 579, 'day': 5}, {'date': '2022-09-18', 'duration': 594, 'day': 6}, {'date': '2022-09-19', 'duration': 524, 'day': 0}, {'date': '2022-09-20', 'duration': 561, 'day': 1}, {'date': '2022-09-21', 'duration': 491, 'day': 2}, {'date': '2022-09-22', 'duration': 531, 'day': 3}, {'date': '2022-09-23', 'duration': 508, 'day': 4}, {'date': '2022-09-24', 'duration': 543, 'day': 5}, {'date': '2022-09-25', 'duration': 505, 'day': 6}, {'date': '2022-09-26', 'duration': 544, 'day': 0}, {'date': '2022-09-27', 'duration': 520, 'day': 1}, {'date': '2022-09-28', 'duration': 481, 'day': 2}, {'date': '2022-09-29', 'duration': 549, 'day': 3}, {'date': '2022-09-30', 'duration': 628, 'day': 4}, {'date': '2022-10-01', 'duration': 488, 'day': 5}, {'date': '2022-10-02', 'duration': 589, 'day': 6}, {'date': '2022-10-03', 'duration': 502, 'day': 0}, {'date': '2022-10-04', 'duration': 481, 'day': 1}, {'date': '2022-10-05', 'duration': 569, 'day': 2}, {'date': '2022-10-06', 'duration': 578, 'day': 3}, {'date': '2022-10-07', 'duration': 515, 'day': 4}, {'date': '2022-10-08', 'duration': 498, 'day': 5}, {'date': '2022-10-09', 'duration': 650, 'day': 6}, {'date': '2022-10-10', 'duration': 547, 'day': 0}, {'date': '2022-10-11', 'duration': 491, 'day': 1}, {'date': '2022-10-12', 'duration': 511, 'day': 2}, {'date': '2022-10-13', 'duration': 538, 'day': 3}, {'date': '2022-10-14', 'duration': 495, 'day': 4}, {'date': '2022-10-15', 'duration': 526, 'day': 5}, {'date': '2022-10-16', 'duration': 505, 'day': 6}, {'date': '2022-10-17', 'duration': 523, 'day': 0}, {'date': '2022-10-18', 'duration': 595, 'day': 1}, {'date': '2022-10-19', 'duration': 550, 'day': 2}, {'date': '2022-10-20', 'duration': 493, 'day': 3}, {'date': '2022-10-21', 'duration': 499, 'day': 4}, {'date': '2022-10-22', 'duration': 604, 'day': 5}, {'date': '2022-10-23', 'duration': 573, 'day': 6}, {'date': '2022-10-24', 'duration': 567, 'day': 0}, {'date': '2022-10-25', 'duration': 623, 'day': 1}, {'date': '2022-10-26', 'duration': 584, 'day': 2}, {'date': '2022-10-27', 'duration': 519, 'day': 3}, {'date': '2022-10-28', 'duration': 597, 'day': 4}, {'date': '2022-10-29', 'duration': 620, 'day': 5}]

            # start_date = datetime.strptime(request.GET.get('start_date'), '%Y-%m-%d')
            # end_date = datetime.strptime(request.GET.get('end_date'), '%Y-%m-%d')
            # qs = self.get_queryset().filter(date__gte=start_date, date__lte=end_date)
            #
            # summary = []
            # for days in range((end_date - start_date).days):
            #     date = start_date + timedelta(days=days)
            #     filtered = qs.filter(date=date)
            #     summary.append({'date': date.strftime('%Y-%m-%d'),
            #                     'duration_in_minutes': sum(obj.duration_in_minutes for obj in filtered),
            #                     'day': date.weekday()})
            # logs = self.serializer_class(qs, many=True)
            # summary = SummarySerailizer(summary, many=True)
            # return Response(data={'logs': logs.data, 'summary': summary.data})
            search = request.GET.get('search')
            temp = logs
            if search:
                search = search.lower()
                temp = [x for x in logs if search in x['description'].lower()]
            return Response(data={'logs': temp, 'summary': summary})
        return super(TimeLoggerViewSet, self).list(request, *args, **kwargs)

    @action(methods=['GET'], detail=False, url_path='weekly-summary')
    def weekly_summary(self, request, *args, **kwargs):
        """
        Always considers the maximum date as the current week.
        ToDo: May need to allow query param to pass two different weeks of the years and filter accordingly
        """
        dt = datetime.strptime(request.query_params.get("date"), '%Y-%m-%dT%H:%M:%S.%fZ')
        qs = self.get_queryset()

        this_start = dt - timedelta(days=(dt.isoweekday() + 1) % 7)
        prev_start = this_start - timedelta(days=7)
        data = {"this_week": {x[0]: x[1].total_seconds() // 60 for x in
                              qs.filter(date__gte=this_start).values("date").order_by("date").annotate(
                                  total=(Sum(F('end') - F('start')))).values_list("date__iso_week_day", "total")},
                "prev_week": {x[0]: x[1].total_seconds() // 60 for x in
                              qs.filter(date__gte=prev_start, date__lt=this_start).values("date").order_by(
                                  "date").annotate(total=Sum(F('end') - F('start'))).values_list("date__iso_week_day",
                                                                                                 "total")}}
        return Response(data)
